SET XAMARIN_FORMS_DIR=C:\Users\chrisk\Documents\git\DuploBuddy\
SET OUT_DIR=c:\output\
SET PACKAGES_DIR=C:\Users\chrisk\Documents\git\King.Mobile\packages\Xamarin.Forms.1.3.0.6275-pre1\lib\

msbuild %XAMARIN_FORMS_DIR%Xamarin.Forms.sln /p:outdir=%OUT_DIR% /m

SET CORE=Xamarin.Forms.Core
SET XAML=Xamarin.Forms.Xaml
SET WP8=Xamarin.Forms.Platform.WP8
SET ANDROID=Xamarin.Forms.Platform.Android
SET IOS=Xamarin.Forms.Platform.IOS.Classic

SET PACKAGES_ANDROID=%PACKAGES_DIR%MonoAndroid10\
SET PACKAGES_IOS=%PACKAGES_DIR%MonoTouch10\
SET PACKAGES_WP8=%PACKAGES_DIR%WP80
SET PACKAGES_PORTABLE=%PACKAGES_DIR%portable-win+net45+wp80+MonoAndroid10+MonoTouch10+Xamarin.iOS10\

COPY /y %OUT_DIR%%CORE%.dll "%PACKAGES_PORTABLE%"
COPY /y %OUT_DIR%%CORE%.pdb "%PACKAGES_PORTABLE%"
COPY /y %OUT_DIR%%XAML%.dll "%PACKAGES_PORTABLE%"
COPY /y %OUT_DIR%%XAML%.pdb "%PACKAGES_PORTABLE%"

COPY /y %OUT_DIR%%CORE%.dll %PACKAGES_ANDROID%
COPY /y %OUT_DIR%%CORE%.pdb %PACKAGES_ANDROID%
COPY /y %OUT_DIR%%XAML%.dll %PACKAGES_ANDROID%
COPY /y %OUT_DIR%%XAML%.pdb %PACKAGES_ANDROID%
COPY /y %OUT_DIR%%ANDROID%.dll %PACKAGES_ANDROID%
COPY /y %OUT_DIR%%ANDROID%.pdb %PACKAGES_ANDROID%

COPY /y %OUT_DIR%%CORE%.dll %PACKAGES_IOS%
COPY /y %OUT_DIR%%CORE%.pdb %PACKAGES_IOS%
COPY /y %OUT_DIR%%XAML%.dll %PACKAGES_IOS%
COPY /y %OUT_DIR%%XAML%.pdb %PACKAGES_IOS%
COPY /y %OUT_DIR%%IOS%.dll %PACKAGES_IOS%
COPY /y %OUT_DIR%%IOS%.dll %PACKAGES_IOS%
COPY /y %OUT_DIR%%IOS%.pdb %PACKAGES_IOS%

COPY /y %OUT_DIR%%CORE%.dll %PACKAGES_WP8%
COPY /y %OUT_DIR%%CORE%.pdb %PACKAGES_WP8%
COPY /y %OUT_DIR%%XAML%.dll %PACKAGES_WP8%
COPY /y %OUT_DIR%%XAML%.pdb %PACKAGES_WP8%
COPY /y %OUT_DIR%%WP8%.dll %PACKAGES_WP8%
COPY /y %OUT_DIR%%WP8%.pdb %PACKAGES_WP8%
